version: 0.1

phases:
  install:
    commands:
      - echo installing nodejs...
      - n 18
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      # - echo testing...
      # - echo building...
      - ng build --configuration production
  post_build:
    commands:
      - mv appspec.yml ./dist
      - mv scripts ./dist
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
